version: '3'
services:
  node:
    image: aeternity/aeternity:v6.8.1
    ports: [3013:3013]
    # TODO: remove after releasing https://github.com/aeternity/aeternity/pull/4292
    healthcheck:
      interval: 2s
    volumes:
      - ./docker/aeternity.yaml:/home/aeternity/node/aeternity.yaml
      - ./docker/accounts.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json
    stop_grace_period: 0s

  compiler:
    image: aeternity/aesophia_http:v7.4.0
    ports: [3080:3080]
    # TODO: remove after releasing https://github.com/aeternity/aesophia_http/pull/133
    healthcheck:
      interval: 2s
