services:
  node:
    image: aeternity/aeternity:v7.3.0-rc3-bundle
    ports: [3013:3013, 3313:3313]
    # TODO: remove after releasing https://github.com/aeternity/aeternity/pull/4292
    healthcheck:
      interval: 2s
    volumes:
      - ./docker/aeternity.yaml:/home/aeternity/node/aeternity.yaml
    stop_grace_period: 0s

  compiler:
    image: aeternity/aesophia_http:v8.0.0
    ports: [3080:3080]
    # TODO: remove after releasing https://github.com/aeternity/aesophia_http/pull/133
    healthcheck:
      interval: 2s
