# yaml-language-server: $schema=https://github.com/aeternity/aeternity/raw/master/apps/aeutils/priv/aeternity_config_schema.json

http:
  endpoints:
    dry-run: true

chain:
  persist: false
  hard_forks:
    "1": 0
    "5": 1

mining:
  autostart: true
  beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
  expected_mine_rate: 1000
  micro_block_cycle: 300
  strictly_follow_top: true
  cuckoo:
    miner:
      executable: mean15-generic
      extra_args: ""
      edge_bits: 15

fork_management:
  network_id: "ae_devnet"
