name: Test
on:
  push:
    branches: [master, develop]
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install --no-install-recommends erlang
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x # minimum supported version
          cache: npm
      - run: npm ci
      - name: Run Commitlint
        if: github.event_name == 'pull_request'
        env:
          HEAD: ${{ github.event.pull_request.head.sha }}
          BASE: ${{ github.event.pull_request.base.sha }}
        run: npx commitlint --from $BASE --to $HEAD --verbose
      - run: npm run lint
      - run: docker compose up -d --wait --quiet-pull
      - name: Ensure that docs are up to date
        run: npm run docs && git diff --exit-code
      - run: npx c8 npm test
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: docker compose logs
        if: always()
